Counter=7

[Command_0]
Command=no-osd change-list glsl-shaders set "~/.config/haruna/shaders/Anime4K_Clamp_Highlights.glsl:~/.config/haruna/shaders/Anime4K_Restore_CNN_VL.glsl:~/.config/haruna/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x2.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x4.glsl:~/.config/haruna/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
Order=0
OsdMessage=Anime4K: Mode A (HQ)
Type=shortcut

[Command_1]
Command=no-osd change-list glsl-shaders set "~/.config/haruna/shaders/Anime4K_Clamp_Highlights.glsl:~/.config/haruna/shaders/Anime4K_Restore_CNN_Soft_VL.glsl:~/.config/haruna/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x2.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x4.glsl:~/.config/haruna/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
Order=1
OsdMessage=Anime4K: Mode B (HQ)
Type=shortcut

[Command_2]
Command=no-osd change-list glsl-shaders set "~/.config/haruna/shaders/Anime4K_Clamp_Highlights.glsl:~/.config/haruna/shaders/Anime4K_Upscale_Denoise_CNN_x2_VL.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x2.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x4.glsl:~/.config/haruna/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
Order=2
OsdMessage=Anime4K: Mode C (HQ)
Type=shortcut

[Command_3]
Command=no-osd change-list glsl-shaders set "~/.config/haruna/shaders/Anime4K_Clamp_Highlights.glsl:~/.config/haruna/shaders/Anime4K_Restore_CNN_VL.glsl:~/.config/haruna/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~/.config/haruna/shaders/Anime4K_Restore_CNN_M.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x2.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x4.glsl:~/.config/haruna/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
Order=3
OsdMessage=Anime4K: Mode A+A (HQ)
Type=shortcut

[Command_4]
Command=no-osd change-list glsl-shaders set "~/.config/haruna/shaders/Anime4K_Clamp_Highlights.glsl:~/.config/haruna/shaders/Anime4K_Restore_CNN_Soft_VL.glsl:~/.config/haruna/shaders/Anime4K_Upscale_CNN_x2_VL.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x2.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x4.glsl:~/.config/haruna/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~/.config/haruna/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
Order=4
OsdMessage=Anime4K: Mode B+B (HQ)
Type=shortcut

[Command_5]
Command=no-osd change-list glsl-shaders set "~/.config/haruna/shaders/Anime4K_Clamp_Highlights.glsl:~/.config/haruna/shaders/Anime4K_Upscale_Denoise_CNN_x2_VL.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x2.glsl:~/.config/haruna/shaders/Anime4K_AutoDownscalePre_x4.glsl:~/.config/haruna/shaders/Anime4K_Restore_CNN_M.glsl:~/.config/haruna/shaders/Anime4K_Upscale_CNN_x2_M.glsl"
Order=5
OsdMessage=Anime4K: Mode C+A (HQ)
Type=shortcut

[Command_6]
Command=no-osd change-list glsl-shaders clr ""
Order=6
OsdMessage=GLSL shaders cleared
Type=shortcut
